services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: renewlabour
      MYSQL_USER: guru
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork
  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - db
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: guru
      DB_PASSWORD: password
      DB_NAME: renewlabour
    networks:
      - mynetwork
    volumes:
      - ./files:/usr/expressdocker/files

networks:
  mynetwork:
    driver: bridge
