services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: guru
      DB_PASSWORD: password
      DB_NAME: renewlabour
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
